[phases.setup]
aptPkgs = ["ffmpeg", "python3-dev", "python3-pip"]
nixPkgs = ["ffmpeg", "python3", "python3Packages.pip"]
nixLibs = []
cmds = [
  "echo 'Removing any trace of disabled_aria...'",
  "rm -rf /nix/store/*disabled_aria*",
  "find / -name 'disabled_aria*' -delete 2>/dev/null || true"
]

[phases.install]
cmds = [
  "echo 'Installing dependencies...'",
  "python -m venv /opt/venv",
  "source /opt/venv/bin/activate",
  "pip install --upgrade pip",
  "pip install -r requirements.txt",
  "python complete_disabled_aria_removal.py || true",
  "python clean_ytdlp_patch.py || true"
]

[phases.build]
cmds = [
  "echo 'Running final cleaning...'",
  "python complete_disabled_aria_removal.py || true",
  "find / -name 'disabled_aria*' -type f -delete 2>/dev/null || true",
  "! command -v disabled_downloader > /dev/null && echo 'SUCCESS: disabled_downloader not found'"
]

[start]
cmd = "python complete_disabled_aria_removal.py && python clean_ytdlp_patch.py && python telegram_downloader.py"

[variables]
YDL_NO_disabled_downloader = "1"
YTDLP_NO_disabled_aria = "1"
HTTP_DOWNLOADER = "native"
YTDLP_DOWNLOADER = "native"
NO_EXTERNAL_DOWNLOADER = "1"
disabled_downloader_DISABLED = "1"
DISABLE_disabled_downloader = "true"
YTDLP_CONFIG = "{\"external_downloader\":null,\"external_downloader_args\":null}"