[build]
builder = "nixpacks"
buildCommand = "echo 'Building the application...'"

[deploy]
startCommand = "python telegram_downloader.py"
restartPolicyType = "always"

[nixpacks]
aptPackages = ["ffmpeg", "python3-dev"]

[variables]
TELEGRAM_BOT_TOKEN = "placeholder_token" # این متغیر با مقدار واقعی در داشبورد Railway جایگزین خواهد شد