[build]
builder = "nixpacks"

[deploy]
startCommand = "python complete_aria2_removal.py && python clean_ytdlp_patch.py && bash railway_startup.sh"
restartPolicyType = "always"

[nixpacks]
aptPackages = ["ffmpeg", "python3-dev"]
dontInstallRecommends = true

[env]
YDL_NO_ARIA2C = "1"
HTTP_DOWNLOADER = "native"
YTDLP_DOWNLOADER = "native"
NO_EXTERNAL_DOWNLOADER = "1"
YTDLP_NO_ARIA2 = "1"
ARIA2C_DISABLED = "1"
DISABLE_ARIA2C = "true"
YTDLP_CONFIG = "{\"external_downloader\":null,\"external_downloader_args\":null}"
