[build]
builder = "nixpacks"
buildCommand = "echo 'BUILDING CLEAN PROJECT' && python railway_deployment_guide.py && python full_custom_dl_removal.py && python clean_ytdlp_patch.py && python complete_custom_dl_removal.py"

[deploy]
startCommand = "python railway_deployment_guide.py && python full_custom_dl_removal.py && python clean_ytdlp_patch.py && python complete_custom_dl_removal.py && python telegram_downloader.py"
restartPolicyType = "always"

[nixpacks]
nixpacksConfigPath = ".nixpacks/environment.toml"
aptPkgs = ["ffmpeg", "python3-dev"]
dontInstallRecommends = true

[env]
YDL_NO_EXTERNAL_DOWNLOADER = "1"
HTTP_DOWNLOADER = "native"
YTDLP_DOWNLOADER = "native"
NO_EXTERNAL_DOWNLOADER = "1"
DISABLE_EXTERNAL_DL = "true"
