[phases.setup]
cmds = [
  "echo 'Setting up clean environment'",
  "find / -name '*null_downloader*' -delete 2>/dev/null || true"
]

[phases.install]
cmds = [
  "pip install --no-cache-dir --upgrade pip",
  "pip install --no-cache-dir -r requirements.txt",
  "python full_custom_dl_removal.py || true",
  "python clean_ytdlp_patch.py || true",
  "python complete_custom_dl_removal.py || true"
]

[phases.build]
cmds = [
  "python full_custom_dl_removal.py || true",
  "python clean_ytdlp_patch.py || true",
  "python complete_custom_dl_removal.py || true"
]

[phases.deploy]
cmds = [
  "python full_custom_dl_removal.py || true",
  "find / -name '*null_downloader*' -type f -delete 2>/dev/null || true"
]

[start]
cmd = "python full_custom_dl_removal.py && python clean_ytdlp_patch.py && python complete_custom_dl_removal.py && python telegram_downloader.py"

[variables]
HTTP_DOWNLOADER = "native"
YTDLP_DOWNLOADER = "native"
NO_EXTERNAL_DOWNLOADER = "1"
DISABLE_EXTERNAL_DL = "true"
YDL_NO_EXTERNAL_DOWNLOADER = "1"
YDL_VERBOSE_NO_EXTERNAL_DL = "1"
